"""
BrickVisualizer - Obsidian Canvas Integration + Auto-Healing

Generates visual pipeline graphs in Obsidian with:
- Color-coded brick health (🟢 green, 🔴 red, 🟡 yellow)
- Error annotations in brick files
- Auto-healing integration with Gemini CLI
"""

import json
import os
import time
from datetime import datetime
from typing import Dict, List, Any, Optional
from pathlib import Path


class BrickVisualizer:
    """
    Generates Obsidian canvas files and manages error annotations.
    
    Canvas node colors:
    - "1" = Red (broken)
    - "3" = Yellow (healing in progress)
    - "5" = Green (healthy)
    """
    
    def __init__(self, vault_path: str, project_name: str = "BrickLang"):
        self.vault_path = Path(vault_path)
        self.project_dir = self.vault_path / project_name
        self.bricks_dir = self.project_dir / "bricks"
        self.canvas_dir = self.project_dir / "canvases"
        
        # Create directories
        self.project_dir.mkdir(exist_ok=True)
        self.bricks_dir.mkdir(exist_ok=True)
        self.canvas_dir.mkdir(exist_ok=True)
    
    def create_pipeline_canvas(
        self, 
        pipeline_name: str,
        bricks: List[Dict[str, Any]],
        connections: List[tuple]
    ) -> str:
        """
        Create an Obsidian canvas file for a pipeline.
        
        Args:
            pipeline_name: Name of the pipeline
            bricks: List of brick dicts with keys: id, name, label, status, error
            connections: List of (from_brick_id, to_brick_id) tuples
        
        Returns:
            Path to the created canvas file
        """
        canvas = {
            "nodes": [],
            "edges": []
        }
        
        # Layout bricks horizontally
        x, y = 0, 0
        node_width = 300
        node_height = 150
        spacing = 50
        
        for i, brick in enumerate(bricks):
            color = self._get_color_for_status(brick.get("status", "unknown"))
            
            # Create brick file reference (relative to vault root)
            brick_file = f"{self.project_dir.name}/bricks/{brick['id']}.md"
            
            canvas["nodes"].append({
                "id": brick["id"],
                "type": "file",
                "file": brick_file,
                "x": x,
                "y": y,
                "width": node_width,
                "height": node_height,
                "color": color
            })
            
            x += node_width + spacing
        
        # Add edges (connections between bricks)
        for i, (from_id, to_id) in enumerate(connections):
            canvas["edges"].append({
                "id": f"edge_{i}",
                "fromNode": from_id,
                "toNode": to_id,
                "fromSide": "right",
                "toSide": "left"
            })
        
        # Write canvas file
        canvas_path = self.canvas_dir / f"{pipeline_name}.canvas"
        with open(canvas_path, 'w', encoding='utf-8') as f:
            json.dump(canvas, f, indent=2)
        
        return str(canvas_path)
    
    def create_brick_note(
        self,
        brick_id: str,
        name: str,
        label: str,
        description: str,
        source_code: str,
        tests: List[Dict],
        status: str = "healthy",
        error: Optional[str] = None
    ) -> str:
        """
        Create an Obsidian markdown note for a brick.
        
        Returns:
            Path to the created note
        """
        note_path = self.bricks_dir / f"{brick_id}.md"
        
        # Build error block if needed
        error_block = ""
        if error:
            error_block = f'''
---

## ⚠️ ERROR

<error>
**Status:** BROKEN  
**Error:** {error}  
**Time:** {datetime.now().isoformat()}  
**Label:** {label}
</error>

---
'''
        
        # Build test block
        test_block = "\n".join([
            f"- **{t.get('label', 'test')}**: `{t['inputs']}` → `{t.get('expected_output', 'N/A')}`"
            for t in tests
        ])
        
        # Create note content
        content = f'''# {name} `[{label}]`

**ID:** `{brick_id}`  
**Status:** {self._get_status_emoji(status)} {status.upper()}  
**Description:** {description}

{error_block}

## Source Code

```python
{source_code}
```

## Tests

{test_block if test_block else "*No tests defined*"}

## Metadata

- **Created:** {datetime.now().isoformat()}
- **Category:** {label.split('-')[0] if '-' in label else 'unknown'}

---

*Generated by BrickLang Visualizer*
'''
        
        with open(note_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return str(note_path)
    
    def update_brick_status(
        self,
        brick_id: str,
        status: str,
        error: Optional[str] = None
    ) -> None:
        """
        Update a brick's status in its Obsidian note.
        Adds/updates <error> block if error is provided.
        """
        note_path = self.bricks_dir / f"{brick_id}.md"
        
        if not note_path.exists():
            return
        
        with open(note_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Update status line
        import re
        content = re.sub(
            r'\*\*Status:\*\* .*',
            f'**Status:** {self._get_status_emoji(status)} {status.upper()}',
            content
        )
        
        # Handle error block
        if error:
            error_block = f'''
---

## ⚠️ ERROR

<error>
**Status:** BROKEN  
**Error:** {error}  
**Time:** {datetime.now().isoformat()}
</error>

---
'''
            # Remove old error block if exists
            content = re.sub(
                r'---\s*\n\s*##\s*⚠️\s*ERROR.*?---\s*\n',
                '',
                content,
                flags=re.DOTALL
            )
            
            # Insert new error block after description
            content = re.sub(
                r'(\*\*Description:\*\* .*\n)',
                r'\1' + error_block,
                content
            )
        else:
            # Remove error block if no error
            content = re.sub(
                r'---\s*\n\s*##\s*⚠️\s*ERROR.*?---\s*\n',
                '',
                content,
                flags=re.DOTALL
            )
        
        with open(note_path, 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _get_color_for_status(self, status: str) -> str:
        """Map status to Obsidian canvas color."""
        status_colors = {
            "healthy": "5",   # Green
            "broken": "1",    # Red
            "healing": "3",   # Yellow
            "unknown": "2"    # Orange
        }
        return status_colors.get(status.lower(), "2")
    
    def _get_status_emoji(self, status: str) -> str:
        """Map status to emoji."""
        status_emojis = {
            "healthy": "🟢",
            "broken": "🔴",
            "healing": "🟡",
            "unknown": "⚪"
        }
        return status_emojis.get(status.lower(), "⚪")
    
    def create_index_note(self, pipeline_name: str, canvas_path: str) -> str:
        """
        Create an index note that embeds the canvas.
        """
        index_path = self.project_dir / f"{pipeline_name}_index.md"
        
        content = f'''# {pipeline_name} Pipeline

![[{Path(canvas_path).name}]]

## Quick Stats

- **Bricks:** See canvas above
- **Status:** Check individual brick notes
- **Last Updated:** {datetime.now().isoformat()}

## How to Use

1. **View the canvas** above to see the pipeline flow
2. **Click on bricks** to see their code, tests, and errors
3. **Red bricks** = broken (auto-healing in progress)
4. **Yellow bricks** = currently healing
5. **Green bricks** = healthy

---

*Auto-generated by BrickLang Visualizer*
'''
        
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return str(index_path)


class AutoHealer:
    """
    Auto-healing system that integrates with Gemini CLI.
    """
    
    def __init__(self, visualizer: BrickVisualizer, max_attempts: int = 3):
        self.visualizer = visualizer
        self.max_attempts = max_attempts
        self.healing_history: Dict[str, List[Dict]] = {}
    
    def attempt_heal(
        self,
        brick_id: str,
        error_message: str,
        repair_prompt: str
    ) -> Dict[str, Any]:
        """
        Attempt to heal a broken brick using Gemini CLI.
        
        Returns:
            {
                "success": bool,
                "attempts": int,
                "fixed_code": str or None,
                "error": str or None
            }
        """
        if brick_id not in self.healing_history:
            self.healing_history[brick_id] = []
        
        attempts = len(self.healing_history[brick_id])
        
        if attempts >= self.max_attempts:
            return {
                "success": False,
                "attempts": attempts,
                "fixed_code": None,
                "error": f"Max healing attempts ({self.max_attempts}) reached"
            }
        
        # Update status to healing
        self.visualizer.update_brick_status(brick_id, "healing", error_message)
        
        # TODO: Integrate with Gemini CLI
        # For now, return a placeholder
        # In real implementation:
        # fixed_code = gemini_cli.execute(repair_prompt)
        
        result = {
            "success": False,
            "attempts": attempts + 1,
            "fixed_code": None,
            "error": "Gemini CLI integration pending"
        }
        
        self.healing_history[brick_id].append({
            "timestamp": time.time(),
            "error": error_message,
            "result": result
        })
        
        return result
    
    def get_healing_stats(self, brick_id: str) -> Dict[str, Any]:
        """Get healing statistics for a brick."""
        history = self.healing_history.get(brick_id, [])
        
        return {
            "total_attempts": len(history),
            "max_attempts": self.max_attempts,
            "can_retry": len(history) < self.max_attempts,
            "last_attempt": history[-1] if history else None
        }


if __name__ == "__main__":
    # Example usage
    visualizer = BrickVisualizer(
        vault_path="C:/Users/MedoRadi/Desktop/Esi world/Esi",
        project_name="BrickLang_Reddit"
    )
    
    # Example bricks
    bricks = [
        {
            "id": "fetch_reddit",
            "name": "Fetch Reddit Posts",
            "label": "net01-1",
            "status": "healthy",
            "error": None
        },
        {
            "id": "parse_posts",
            "name": "Parse Post Data",
            "label": "parse01-1",
            "status": "broken",
            "error": "KeyError: 'title'"
        },
        {
            "id": "save_obsidian",
            "name": "Save to Obsidian",
            "label": "io01-1",
            "status": "healthy",
            "error": None
        }
    ]
    
    connections = [
        ("fetch_reddit", "parse_posts"),
        ("parse_posts", "save_obsidian")
    ]
    
    # Create canvas
    canvas_path = visualizer.create_pipeline_canvas(
        "reddit_to_obsidian",
        bricks,
        connections
    )
    
    print(f"Created canvas: {canvas_path}")
    
    # Create brick notes
    for brick in bricks:
        note_path = visualizer.create_brick_note(
            brick_id=brick["id"],
            name=brick["name"],
            label=brick["label"],
            description="Example brick",
            source_code="def example():\n    pass",
            tests=[],
            status=brick["status"],
            error=brick.get("error")
        )
        print(f"Created note: {note_path}")
    
    # Create index
    index_path = visualizer.create_index_note("reddit_to_obsidian", canvas_path)
    print(f"Created index: {index_path}")
    
    print("\n✅ Obsidian integration ready!")
